<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelInventory" nsURI="http://www.example.org/modelInventory"
    nsPrefix="modelInventory">
  <eClassifiers xsi:type="ecore:EClass" name="ModelInventory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" upperBound="-1"
        eType="#//Language" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" upperBound="-1"
        eType="#//Model" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collaborationSessions"
        upperBound="-1" eType="#//CollaborationSession" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedEditors" upperBound="-1"
        eType="#//Editor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//LocationType"
        defaultValueLiteral="URL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="confirmsTo" lowerBound="1"
        eType="#//Language"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollaborationSession">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//Participant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Editor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EditorType"
        defaultValueLiteral="TEXTUAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//RoleType"
        defaultValueLiteral="COLLABORATOR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RoleType">
    <eLiterals name="INITIATOR"/>
    <eLiterals name="COLLABORATOR" value="1"/>
    <eLiterals name="OWNER" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LocationType">
    <eLiterals name="URL"/>
    <eLiterals name="GIT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EditorType">
    <eLiterals name="TEXTUAL"/>
    <eLiterals name="GRAPHIC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
